spring:
  datasource:
    url: ${vcap.services.sales-db.credentials.uri}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    com.baskettecase.ordersmcp: INFO 